=== maggie1000/dbmorph/scratch/oracle/deltas-svn-external/dbManagerConf.dtd
<!ELEMENT db_manager_conf (svn_repo_uri, sql_directory, branches?)>

<!ELEMENT svn_repo_uri (#PCDATA)>
<!ELEMENT sql_directory (#PCDATA)>

<!ELEMENT branches (branch*)>
<!ELEMENT branch (name, last_update_from_trunk, deltas?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT last_update_from_trunk (#PCDATA)>
<!ELEMENT deltas (delta*)>
<!ELEMENT delta (#PCDATA)>
<!ATTLIST delta src CDATA #REQUIRED>
<!ATTLIST delta original_branch CDATA #IMPLIED>

=== maggie1000/dbmorph/scratch/oracle/deltas-svn-external/dbManagerConf.xml
<?xml version="1.0"?>
<!DOCTYPE db_manager_conf SYSTEM "dbManagerConf.dtd">

<db_manager_conf>
    <svn_repo_uri>https://myrepo.com/svn/myapp/</svn_repo_uri>
    <sql_directory>sql</sql_directory>

    <branches>
        <branch>
            <name>trunk</name>
            <last_update_from_trunk>0</last_update_from_trunk>
            <deltas>
                <delta src="db_deltas/deltas">1</delta>
                <delta src="db_deltas/deltas">2</delta>
                <delta src="db_deltas/deltas" original_branch="2.2">3</delta>
            </deltas>
        </branch>
        <branch>
            <name>2.2</name>
            <last_update_from_trunk>2</last_update_from_trunk>
            <deltas>
                <delta src="db_deltas/deltas">3</delta>
            </deltas>
        </branch>
    </branches>
</db_manager_conf>
