=== maggie1000/dbmorph/scratch/oracle/deltas-svn-external/update.dtd
<!ELEMENT update (summary, schema, up, down, packages?, jobs?)>
<!ATTLIST update number CDATA #REQUIRED>

<!ELEMENT summary (#PCDATA)>
<!ELEMENT schema (#PCDATA)>
<!ELEMENT up (#PCDATA)>
<!ELEMENT down (#PCDATA)>

<!ELEMENT packages (package*)>
<!ELEMENT package (pkg, pkg_body)>
<!ELEMENT pkg (#PCDATA)>
<!ELEMENT pkg_body (#PCDATA)>

<!ELEMENT jobs (up, down)>

=== maggie1000/dbmorph/scratch/oracle/deltas-svn-external/1.xml
<?xml version="1.0"?>
<!DOCTYPE update SYSTEM "update.dtd">

<update number="1">
    <summary>Install the SCHEMA_VERSION table and associated sequence and packages to support the database manager tool.</summary>
    <schema>main</schema>

    <up>
<![CDATA[
create sequence schema_version_seq nocache;

create table schema_version(
    id integer not null primary key,
    last_update_ran varchar2(32) not null
        constraint schema_version_version_uk unique,
    summary varchar2(2000) not null,
    last_ran date not null
);

]]>
    </up>

    <down>
<![CDATA[
drop package schema_version_pkg;
drop table schema_version;
drop sequence schema_version_seq;

]]>
    </down>

    <packages>
        <package>
            <pkg>MyApp/SchemaVersion/pkg.sql</pkg>
            <pkg_body>MyApp/SchemaVersion/pkg_body.sql</pkg_body>
        </package>
    </packages>
</update>

=== maggie1000/dbmorph/scratch/oracle/deltas-svn-external/example.xml
<?xml version="1.0"?>
<!DOCTYPE update SYSTEM "update.dtd">

<update number="0">
    <summary>This update does X.</summary>

    <schema>main</schema>

    <up>
<![CDATA[
    -- Change you want installed.
    create table test_table (field1 varchar2(1));

    -- If you don't have any DDL to run, put a comment like this:
    -- No DDL to run.


]]>
    </up>

    <down>
<![CDATA[
    -- How to uninstall the change.
    drop table test_table;


]]>
    </down>

    <packages>
        <package>
            <pkg>MyApp/Test/pkg.sql</pkg>
            <pkg_body>MyApp/Test/pkg_body.sql</pkg_body>
        </package>
        <package>
            <pkg>MyApp/Test2/pkg.sql</pkg>
            <pkg_body>MyApp/Test2/pkg_body.sql</pkg_body>
        </package>
    </packages>

    <jobs>
        <up>
        begin
            dbms_scheduler.create_job(
                job_name => 'test_job',
                job_type => 'plsql_block',
                job_action => 'begin test_pkg.run_test; end;',
                repeat_interval => 'freq=daily;byhour=0;',
                enabled => true,
                comments => '');
        end;
/
show errors

        </up>

        <down>
        begin
            dbms_scheduler.drop_job(
                job_name => 'test_job',
                force => true
            );
        end;
/
show errors

        </down>
    </jobs>
</update>
